### ISSUE TITLE
Double Notification on Build abort/fail

### ISSUE THREAD

**Issue by odini** [jenkinsci/cisco-spark-notifier-plugin#3]
We are using this plugin 1.0.1 with Jenkins 2.23. We have configured the plugin to send notifications on aborts or failures. For every build, we get two notifications instead of one. Any idea why? Thanks

**Comment by taylorp36** [comment]
Hi, I cannot reproduce this issue. If you are still facing the issue, could you provide information of what the console log looks like? Do you see 2 messages being sent in the log?
