### ISSUE TITLE
Jenkins behind proxy

### ISSUE THREAD

**Issue by puppetmaster-** [jenkinsci/cisco-spark-notifier-plugin#5]
Hello,

our Jenkins installation is behind an internet proxy. 

We got following message:

`Sending message to Spark Room: 001a1510-4a83-11e7-af0f-bf62e4939ba3
Could not send message because of an unknown issue; please an issue
`
Are there any plans to support Jenkins installations behind an internet proxy or how could we solve this problem?

Thanks for any tips or suggestions.

Christian

**Comment by taylorp36** [comment]
One option is to set -Dhttps.proxyHost and -Dhttps.proxyPort as JVM arguments when starting up jenkins. Is this feasible in your setup?

**Comment by johnboscor** [comment]
I have the same problem. My machine is not behind any proxy and still the request times out as above. Any suggestions?

**Comment by taylorp36** [comment]
@johnboscor could you give some details about your network environment? Does the following command work from your jenkins master, if you have access?

`curl -X POST -v \
"https://api.ciscospark.com/v1/messages" \
-H "Content-Type: application/json" \
-H "Authorization: Bearer  your-token-here" \
-d '{"roomId": "your-room-id", "text": "test"}'`
